/* sync.js v1 - Radar Eventos Paraello - last-write-wins, sem senha */
var API='/api/state',ready=false,_ver=0,pushTimer=null,pushing=false,pendingPush=false;
var _set=localStorage.setItem.bind(localStorage),_rem=localStorage.removeItem.bind(localStorage),_clear=localStorage.clear.bind(localStorage);
function snapshot(){var o={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);o[k]=localStorage.getItem(k);}return o;}
function doPush(){if(!ready)return;if(pushing){pendingPush=true;return;}pushing=true;fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseV:_ver,data:snapshot()})}).then(function(r){return r.ok?r.json():null;}).then(function(j){if(j&&typeof j.v==='number')_ver=j.v;}).catch(function(){}).finally(function(){pushing=false;if(pendingPush){pendingPush=false;schedulePush();}});}
function schedulePush(){clearTimeout(pushTimer);pushTimer=setTimeout(function(){pushTimer=null;doPush();},1000);}
localStorage.setItem=function(k,v){_set(k,v);if(ready)schedulePush();};
localStorage.removeItem=function(k){_rem(k);if(ready)schedulePush();};
window.__cloudHydrate=function(startApp){fetch(API,{method:'GET',headers:{'Content-Type':'application/json'}}).then(function(r){return r.ok?r.json():Promise.reject(new Error('http '+r.status));}).then(function(resp){_ver=typeof resp.v==='number'?resp.v:0;var data=resp.data,hadData=data&&typeof data==='object'&&Object.keys(data).length>0;if(hadData){_clear();Object.keys(data).forEach(function(k){_set(k,data[k]);});}ready=true;try{startApp();}catch(e){console.error(e);}if(!hadData)schedulePush();}).catch(function(err){if(String(err.message)!=='unauthorized'){ready=true;try{startApp();}catch(e){console.error(e);}}});};
function hasPending(){return ready&&(pushTimer||pushing||pendingPush);}
function flushNow(){if(!ready)return;clearTimeout(pushTimer);pushTimer=null;doPush();}
document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')flushNow();});
window.addEventListener('pagehide',function(){flushNow();});
window.addEventListener('beforeunload',function(e){if(hasPending()){flushNow();e.preventDefault();e.returnValue='';}});
var POLL_MS=6000,_checking=false,_applying=false;
function isEditing(){try{var el=document.activeElement;if(!el)return false;if(el.tagName==='TEXTAREA'||el.isContentEditable)return true;if(el.tagName==='INPUT'){var t=(el.getAttribute('type')||'text').toLowerCase();return t!=='checkbox'&&t!=='radio'&&t!=='button'&&t!=='submit'&&t!=='reset';}if(document.querySelector('.modal.open'))return true;}catch{}return false;}
function applyRemote(){if(_applying)return;_applying=true;fetch(API,{method:'GET',headers:{'Content-Type':'application/json'}}).then(function(r){return r.ok?r.json():null;}).then(function(resp){if(!resp)return;_ver=typeof resp.v==='number'?resp.v:_ver;var data=resp.data;if(!data||typeof data!=='object')return;_clear();Object.keys(data).forEach(function(k){_set(k,data[k]);});try{if(typeof loadState==='function')loadState();}catch{}try{if(typeof renderAll==='function')renderAll();}catch{}try{var el=document.getElementById('__cloudUpdate');if(el)el.remove();}catch{}}).catch(function(){}).finally(function(){_applying=false;});}
function showUpdateBanner(){if(document.getElementById('__cloudUpdate'))return;var d=document.createElement('div');d.id='__cloudUpdate';d.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2147483647;background:#1a6fe8;color:#fff;padding:13px 18px;border-radius:10px;font-family:sans-serif;font-size:14px;box-shadow:0 8px 28px rgba(0,0,0,.45)';d.innerHTML='Outra pessoa salvou. <button id="__cloudUpdateBtn" style="margin-left:6px;background:#fff;color:#1a6fe8;border:0;border-radius:6px;padding:7px 14px;font-weight:700;cursor:pointer">Atualizar</button>';(document.body||document.documentElement).appendChild(d);var btn=document.getElementById('__cloudUpdateBtn');if(btn)btn.onclick=applyRemote;}
function checkRemote(){if(!ready||_checking)return;if(hasPending()||pushing)return;_checking=true;fetch(API+'?v=1',{method:'GET',headers:{'Content-Type':'application/json'}}).then(function(r){return r.ok?r.json():null;}).then(function(j){if(j&&typeof j.v==='number'&&j.v>_ver){if(isEditing())showUpdateBanner();else applyRemote();}}).catch(function(){}).finally(function(){_checking=false;});}
setInterval(checkRemote,POLL_MS);
document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')checkRemote();});
window.cloudRefresh=function(){location.reload();};
